import sys


def show_error_and_exit(error):
    print(error)
    sys.exit(1)
